### PR TITLE
fix: typings and margin call

### PR DESCRIPTION
**Pull request by yovanoc**

### CODE REVIEW

**Comment by balthazar** [comment]
Thanks! Can you prettify?

**Comment by yovanoc** [comment]
I ran prettier on this already

**Comment by balthazar** [comment]
There's tabs in there so I doubt it considering we use spaces

**Comment by yovanoc** [comment]
Its spaces. Look the first file, it removes an unwanted space too, I sear a ran prettier on this ^^

**Comment by yovanoc** [comment]
Ok I just did on the js files too. But it changes a lot of things...

**Comment by balthazar** [comment]
Thanks @yovanoc!

@Raphael0010 t'as pas d'autres choses plus interessantes a faire?

**Comment by Raphael0010** [comment]
> Thanks @yovanoc!
> 
> @Raphael0010 t'as pas d'autres choses plus interessantes a faire?

Rho

**Pull request merged**
