### PR TITLE
Fix for futuresCancelAllOpenOrders and futuresBatchOrders

### PR DESCRIPTION
**Pull request by luzianscherrer**
- Fixed missing arguments in futuresCancelAllOpenOrders
- Fixed typo in path of futuresCancelAllOpenOrders and futuresBatchOrders

### CODE REVIEW

**Comment by balthazar** [comment]
Thanks!

**Comment by 4tj** [comment]
But `futuresCancelAllOpenOrders` not define in `d.ts`

**Comment by aweiu** [comment]
But futuresCancelAllOpenOrders not define in d.ts

**Comment by aweiu** [comment]
> But `futuresCancelAllOpenOrders` not define in `d.ts`

+ `futuresBatchOrders`

**Pull request merged**
