### PR TITLE
feat: add custom sub stream

### PR DESCRIPTION
**Pull request by THROFHR**

### CODE REVIEW

**Comment by balthazar** [comment]
Neat, do you mind documenting them in the readme?

**Comment by THROFHR** [comment]
> Neat, do you mind documenting them in the readme?

Sorry, I didn't understand what you mean.

I am not sure if my modification will be useful to others
I found that there are many methods that have not been encapsulated in the process of using this library. I hope there is a low-level method that developers can handle by themselves

**Comment by balthazar** [comment]
Just add them in the readme, so these developers can find them more easily rather than looking at the code itself

**Comment by THROFHR** [comment]
> Just add them in the readme, so these developers can find them more easily rather than looking at the code itself

Of course, if you add it, I will be very happy。

**Pull request merged**
