### PR TITLE
docs: typings and margin call event

### PR DESCRIPTION
**Pull request by yovanoc**

### CODE REVIEW

**Comment by balthazar** [comment]
fix the indentation

**Comment by yovanoc** [comment]
image

This is normal?

**Comment by balthazar** [comment]
Thanks!

**Comment by bennycode** [comment]
@yovanoc why did you remove `minNotional` from the `SymbolMinNotionalFilter`? It still exists in: https://binance-docs.github.io/apidocs/spot/en/#filters

**Format:**

```json
 {
    "filterType": "MIN_NOTIONAL",
    "minNotional": "0.00100000",
    "applyToMarket": true,
    "avgPriceMins": 5
  }
```

You can also see it here: https://github.com/binance/binance-spot-api-docs/blob/master/rest-api.md#min_notional

@balthazar we have to be really careful when making such big changes to the types. My TypeScript program now fails with error message:

>  error TS2339: Property 'minNotional' does not exist on type 'SymbolMinNotionalFilter'.

**Comment by yovanoc** [comment]
Ohhhh right we have to differentiate futures and spot types then

**Comment by NorthBlue333** [comment]
I agree. It breaks my project. I am going to cast as a workaround and disabling updates for this package so types won't be broken again.

**Comment by FahriDevZ** [comment]
@bennycode Talking about SymbolFilters, this pull was break interface  `SymbolMinNotionalFilter` and `SymbolPercentPriceFilter`

```diff
export interface SymbolMinNotionalFilter {
  filterType: SymbolFilterType.MIN_NOTIONAL
-  applyToMarket: boolean
-  avgPriceMins: number
-  minNotional: string
+  notional: string
}

export interface SymbolPercentPriceFilter {
  filterType: SymbolFilterType.PERCENT_PRICE
  multiplierDown: string
  multiplierUp: string
-  avgPriceMins: number
+  multiplierDecimal: number
}
```

I was solve this issue by create custom declare type definition

```ts
declare module 'binance-api-node' {
  export interface SymbolMinNotionalFilter {
    filterType: SymbolFilterType.MIN_NOTIONAL;
    applyToMarket: boolean;
    avgPriceMins: number;
    minNotional: string;
  }

  export interface SymbolPercentPriceFilter {
    filterType: SymbolFilterType.PERCENT_PRICE;
    multiplierDown: string;
    multiplierUp: string;
    avgPriceMins: number;
  }
}
```

But my question is what `multiplierDecimal` in SymbolPercentPriceFilter? and `notional` in SymbolMinNotionalFilter? i'm really confused because is different with binance docs example format :'(

**Pull request merged**
