### PR TITLE
add ability to specify custom endpoints for web sockets

### PR DESCRIPTION
**Pull request by harshitgupta**
The function was already implemented was http client. 

Please let me know if you want me to make additional changes.

### CODE REVIEW

**Comment by lucas-labs** [comment]
@balthazar Hi! This would be really useful in the case you need to send requests through a proxy. Or if you want to test your app by hitting the testnet endpoints. If there is something I can do to help get this PR merged, please let me know :)
Thanks!

**Comment by jorisw** [comment]
@harshitgupta Resolving the conflicts in this PR may help speed up merging

**Comment by jorisw** [comment]
Dupe of #278

**Comment by balthazar** [comment]
Closing in favor of 4189f6130d77afa9ff5f8c5ee7ea2e34ff2071cf

**Pull request closed without merging**
