### PR TITLE
Fix typescript enum importing issue by replacing string enums with literal types

### PR DESCRIPTION
**Pull request by sxwei123**
Should be able to closes these issues:
https://github.com/Ashlar/binance-api-node/issues/463
https://github.com/Ashlar/binance-api-node/issues/479
https://github.com/Ashlar/binance-api-node/issues/459

### CODE REVIEW

**Comment by sxwei123** [comment]
With [literal types](https://www.typescriptlang.org/docs/handbook/literal-types.html), the typescript developers will be able to have same experience as JS developer:
```ts
await client.order({
    symbol: 'XLMETH',
    side: 'BUY',
    quantity: '100',
    price: '0.0002',
  })
```
instead of:
```ts
await client.order({
    symbol: 'XLMETH',
    side: OrderType.BUY,
    quantity: '100',
    price: '0.0002',
  })
```

**Comment by balthazar** [comment]
@malikfaik any comment since you're the one who made those?

**Comment by balthazar** [comment]
@bennycode

**Comment by balthazar** [comment]
Deferring to you, master typings 😄

**Comment by balthazar** [comment]
Superseeded by #489

**Comment by sxwei123** [comment]
#489 is still not correct.
It is just cheating the TS compiler. After the ts code got compiled to js, there will be exceptions since those enums are not exported from the js project.
Try to compile this to js and run the js with node, you will find an `SyntaxError: Cannot use import statement outside a module`.

```ts
import { OrderType } from "binance-api-node";
```

**Pull request closed without merging**
