### PR TITLE
Add Notional and Leverage Brackets

### LINKED ISSUE #416: add GET /fapi/v1/leverageBracket

### PR DESCRIPTION
**Pull request by jstoeffler**
Fix #416
https://binance-docs.github.io/apidocs/futures/en/#notional-and-leverage-brackets-user_data

### CODE REVIEW

**Comment by balthazar** [comment]
Thanks! Can you also add it to the readme?

**Comment by balthazar** [comment]
Parfait merci 😄

**Comment by jstoeffler** [comment]
Avec plaisir 😉

By the way I didn't get the chance to test it manually 🙈 
I've tried but I don't know how to build it in a way that I can replace the node_modules/binance-api-node folder in my project.

I think it would be nice to test it before doing a release, so either someone does it, or I would need some instructions on how to build it as a module.

**Comment by balthazar** [comment]
Well it's an addition, so it's not like it will break anything. If you want to test a local module, you can simply do `yarn link` in your local copy of binance-api-node and `yarn link binance-api-node` in the repo that uses it, so it links to your local version for debugging purposes. You'll just have to run `yarn build` in this repo before to create the dist files

**Pull request merged**
