### PR TITLE
multiple fixes (trades stream, ts declaration file)

### PR DESCRIPTION
**Pull request by MohamedLamineAllal**
I'm using typescript and i encountred that. I don't know why it was so. But there is a complete incoherence between the types i changed and the binance api or for what is published in the readme. I checked the implementation and all, it seem a mistake. thank you for reviewing that.

### CODE REVIEW

**Comment by balthazar** [comment]
https://github.com/Ashlar/binance-api-node#authenticated-rest-endpoints

For all authed endpoints you can pass this param. What was your issue exactly?

**Comment by MohamedLamineAllal** [comment]
My issue was with typescript! type checking go wrong.
I looked up the code. I know i can. Also it's nice to have the right parameters in your code editor with the definitions helpers. Thank you for the great work

**Comment by MohamedLamineAllal** [comment]
halo there. 
Not gonna merge !!!!
I have a new pull request that fix some important things. I need that merged first.

**Comment by MohamedLamineAllal** [comment]
To explain the last commit
Screenshot from 2019-10-03 05-32-17
From the binance package. And it's a more right when it come to names.

**Comment by balthazar** [comment]
`useServerTime` comes from this lib, so you should add it back to the type definitions.

>(don't know why you shopped some. Specially tradeTime)

You know APIs are subject to change and the Binance one is no exception, it's probably something they added after I created the lib.

**Comment by MohamedLamineAllal** [comment]
AggTrades too is different. I fixed it too. Let me sort all things well. I will let you know to review and merge.

**Comment by MohamedLamineAllal** [comment]
Hi there again. 
Please review now and merge. 
> useServerTime comes from this lib, so you should add it back to the type definitions.
i get it well now. Last time i asked about it. I put it back. And the last changes except for removing this all stand.

Then for this time changes here the resume. The library have some serious issues and it's not matching the official api. 

For example:
image
the id is completely wrong.

I added all the data that is exposed from the official doc. 

Some changes in the names of the properties. So it will be consistent with the rest. 
Screenshot from 2019-10-03 08-20-06
created separate type for Ws and normal rest api.
They were completely inconsistent.

Screenshot from 2019-10-03 08-20-22
Changed only to be consistent with the rest (as every where else it's time that is used)
Screenshot from 2019-10-03 08-21-14
Screenshot from 2019-10-03 08-20-57
I used is best match because you by yourself you used in many places. And without that the aggTrades are handled manually and explicitly. And trades get it directly from the api whatever it is. And it just use isBestMatch.
Screenshot from 2019-10-03 08-23-53
Screenshot from 2019-10-03 08-23-35
And that inconsistency can be clearly seen in the doc itself.

I updated the doc to reflect all made changes.

Please review and merge.

Also i handled only the methods i needed myself. More methods may need changing. Whenever i get something i will send a PR.
And thank you. At first day i kept wondering why he didn't accept it. It was just simple types. And the useServerTime that i removed created all the confusion. 

Thank you again.

**Comment by balthazar** [comment]
@bennyn Could you take a look at this too since you're familiar with the typings? Did the Binance api change recently?

**Comment by bennyn** [comment]
@MohamedLamineAllal Thanks for your contribution but I see several mistakes in your PR:
1. Your response payload in the `README.md` for "trades" is wrong. The call is executed for the pairs `['ETHBTC', 'BNBBTC']` but your response symbol is "BTCUSDT".
1. Your response payload in the `README.md` for "aggTrades" is wrong. The call is executed for the pairs `['ETHBTC', 'BNBBTC']` but your response symbol is "BTCUSDT".
1. Changing `declare module 'binance-api-node'` to `declare module 'binance-client'` is a fatal mistake as the npm package is called `binance-api-node`.
1. Widening the return type of the WebSocket's return type from `ReconnectingWebSocketHandler` to `Function` is also a conflict with our typing system because now it's not explicit anymore and third-party users won't be notified of the parameters which the function carries.

In your PR you are addressing many "problems" at once. To make reviewing easier I advise you to create one PR per each conflicting area you found.

@balthazar I advise you to close this PR.

**Comment by MohamedLamineAllal** [comment]
@bennyn Yea i can see that. I don't know for the last one why i did that. It was last time. And for binance-client it was a stupid copy past mistake too. As i created a fork.

There is however an important need to review and decide the current state of the package. It's obsolete half way. And it have dangerous wrong data in another due to the wrong parsing of the output (parsing here mean just the construction of the final output from the original output).

The important thing that i want you to consider after i do is the naming of the properties in the outputs. And there types as i just found that many or all the number values like price and qty (quantity) are typed as string. I'm changing that to number. I haven't checked yet how internally it's handled. But i can add parsing. Any way i will have a proposition. When i do  i will detail it so it will be simple to understand and get.

I will fill a PR that handle all that at once. As it's related. Make the package up to date. And that involve the internal, typescript declaration, and the doc.

Also i come to commit the changes for the errors you pointed. I think it's better to update and have something working. Right now. Then when thought well we can update again. You know better so it's up to you. I'm managing a fork for my project. 

Thank you a lot.

**Comment by MohamedLamineAllal** [comment]
I will reopen when i handle everything cleanly

**Pull request closed without merging**
