### PR TITLE
TS Definition Updates

### PR DESCRIPTION
**Pull request by DakotaLarson**
Fixes issue: https://github.com/Ashlar/binance-api-node/issues/239

This PR also includes types for futures methods.

Thoughts? The accuracy of the methods as they are currently implemented is not 100%. This PR doesn't fix that, and updating all the types is a major operation. It's something I can take a look into, but I wanted to see what the thoughts are on this solution before investing the time.

Thanks!

### CODE REVIEW

**Comment by balthazar** [comment]
Looking good! Would you mind using `//` comments or remove the line if it's not being used

**Comment by DakotaLarson** [comment]
Addressed! Just to touch on that. This method is in the docs, but not in the implementation as far as I can tell. Can't find anything in the Binance futures docs either about this method / endpoint. If it doesn't exist, then I can just take that line out + the section in the README. Thoughts?

**Comment by balthazar** [comment]
Yeah please take it out, thanks!

**Comment by DakotaLarson** [comment]
Done!

**Comment by balthazar** [comment]
Thanks!

**Pull request merged**
