### PR TITLE
Update typings for Trade interface

### PR DESCRIPTION
**Pull request by gr8den**

### CODE REVIEW

**Comment by balthazar** [comment]
@bennycode Looking good?

**Comment by bennycode** [comment]
In the [API changelog](https://binance-docs.github.io/apidocs/spot/en/), [REST API docs](https://github.com/binance/binance-spot-api-docs/blob/master/rest-api.md) and [Swagger definition](https://github.com/binance-exchange/binance-api-swagger/blob/master/spot_api.yaml) I cannot find a trace to `tradeTime`, `buyerOrderId` or `sellerOrderId`.

When executing `await client.trades({symbol: 'LTCUSDT'})`, I am getting returned this:

```js
[
  {
    id: 50167927,
    price: '106.36000000',
    qty: '0.30000000',
    quoteQty: '31.90800000',
    time: 1565245913483,
    isBuyerMaker: false,
    isBestMatch: true
  },
  ...
]
```

So there is no proof for the existence of these values. 

@gr8den can you tell us where you spotted the properties that you want to add to the `Trade` interface?

**Comment by gr8den** [comment]
It is Trade from WebSocket event
Example:
```js
{
  eventType: 'trade',
  eventTime: 1609402491309,
  tradeTime: 1609402491308,
  symbol: 'BTCUSDT',
  price: '29024.68000000',
  quantity: '0.03425500',
  isBuyerMaker: false,
  maker: true,
  tradeId: 535800815,
  buyerOrderId: 4094506862,
  sellerOrderId: 4094506624
}
```

It turns out that WS & Rest have different Trade interfaces

**Comment by bennycode** [comment]
Ok, I am okay with the extension of the `Trade` interface. 👍

**Review by bennycode — APPROVED** [review]

**Comment by balthazar** [comment]
Thanks!

**Pull request merged**
