### PR TITLE
Fix wrongly named function types (liquidation streams)

### PR DESCRIPTION
**Pull request by phl3x0r**
fixes wrongly named function types:
futuresLiquidations
futuresAllLiquidations

### CODE REVIEW

**Comment by balthazar** [comment]
Can you rebase and do a clean pr?

**Comment by phl3x0r** [comment]
Forgot to add name changes to the index.d.ts file. Sorry about that!

**Comment by phl3x0r** [comment]
sure will rebase, no problem

**Comment by balthazar** [comment]
I don't quite get why the diff looks like that for the typings

**Pull request closed without merging**
