### PR TITLE
add OrderSide implementation

### PR DESCRIPTION
**Pull request by daniildxb**
partly fixes issues described in https://github.com/Ashlar/binance-api-node/issues/459

### CODE REVIEW

**Comment by balthazar** [comment]
Are you sure you are on the latest?

**Comment by daniildxb** [comment]
I'm on 0.11.10

**Comment by balthazar** [comment]
Why would we need to add an object in the source that's unused just for typescript? It's going to create lint errors

**Comment by daniildxb** [comment]
I don't think it's expected that usage of defined types will throw errors

**Comment by balthazar** [comment]
It's an issue to be solved in the type definition, not in the source.

**Pull request closed without merging**
