### PR TITLE
Make marginActiveAccount

### PR DESCRIPTION
**Pull request by luckypal**
User can active or inactive margin isolated trading pair with this method.

### CODE REVIEW

**Comment by balthazar** [comment]
You should prob keep this method and add an enableMarginAccount for backwards compatibility purposes, or create a `toggleMarginAccount` instead and keep the existing one for now

**Comment by luckypal** [comment]
Okay

**Comment by luckypal** [comment]
Updated.

**Comment by balthazar** [comment]
Thanks!

**Pull request merged**
