### PR TITLE
Fix #240: Add 'ping' listener to WS streams

### LINKED ISSUE #240: Add 'ping' listener for websockets
According to [official documentation](https://github.com/binance-exchange/binance-official-api-docs/blob/master/web-socket-streams.md) I should listen `ping` messages and reply `pong` message in my websocket channels:

> The websocket server will send a ping frame every 3 minutes. If the websocket server does not receive a pong frame back from the connection within a 10 minute period, the connection will be disconnected.

Maybe it's also about #123

### PR DESCRIPTION
**Pull request by alexeymarunin**
A little fix to avoid multiple WS reconnect (trades, klines, user streams, etc)

### CODE REVIEW

**Comment by balthazar** [comment]
Can you base your changes of off my master branch so it doesn't have all your other commits?

**Comment by alexeymarunin** [comment]
@balthazar 
Sorry, I'm not good in github PRs and don't quite understand how to do this (( 
But if you explain me I'll try

**Comment by balthazar** [comment]
Lots of ways to do it, you could have reseted your fork master branch and done your commit after, you could have created a patch file by doing the diff too. If you want to though to make it easier I can close this PR and implement this fix

**Comment by alexeymarunin** [comment]
@balthazar,

Feel free to make it by easest way)

**Comment by balthazar** [comment]
Курто! Спасибо!

**Comment by balthazar** [comment]
Actually are you sure it's not done automatically by the reconnect lib by default?

**Comment by alexeymarunin** [comment]
I'm sure the reconnecting-websocket works fine) But while reconnecting it can lose some important incoming data (especially trades or order/balance updates). And I think we should use _native_ way to stay online as long as possible)

**Comment by balthazar** [comment]
What I'm saying is that I was wondering if the library itself already replies with a pong when a ping is received, and thus the code isn't helpful in any way. Have you tested that no pong is emitted?

**Comment by alexeymarunin** [comment]
If you mean reconnecting-websocket's ping() I couldn't find that method, so I offered you my solution.

Please see [reconnectiong-websocket #23](https://github.com/pladaria/reconnecting-websocket/issues/23) issue

**Comment by balthazar** [comment]
Sounds good, deployed a new version implementing the fix

**Pull request closed without merging**
