### PR TITLE
add: futuresCancelBatchOrders

### PR DESCRIPTION
**Pull request by jinusean**
Implements 'Cancel Multiple Orders' https://binance-docs.github.io/apidocs/futures/en/#cancel-multiple-orders-trade.

Also includes missing 'futuresBatchOrders' typings definition.

### CODE REVIEW

**Comment by balthazar** [comment]
Thanks! Do you mind adding those methods to the README?

**Comment by jinusean** [comment]
@balthazar sorry just noticed your message, the README has been updated!

**Comment by balthazar** [comment]
@jinusean Hello! No problem 😄 Do you mind removing your changes to the gitignore that are out of scope of the PR so it solves conflicts and I get go ahead and merge it?

Thanks!

**Comment by jinusean** [comment]
@balthazar done!

**Comment by balthazar** [comment]
Thank you!

**Pull request merged**
