### PR TITLE
Updates for NewOrder types

### PR DESCRIPTION
**Pull request by krolov**
Hi @balthazar ! 
As I promise before new types of orders create. 
It would be nice if @bennycode also looks it.

I don't do it for futures, cause I see a separate PR for futures order types and prefer don't touch it before merge .

### CODE REVIEW

**Comment by balthazar** [comment]
Hello @krolov, looking good thanks! Think I'll merge #468 first and then wait a bit to see if benny has some time to take a look at that one

**Comment by krolov** [comment]
@bennycode softly remind :-)

**Comment by bennycode** [comment]
@krolov I see that you removed the usage of `NewOrder`. Can you also remove that interface completely?

**Comment by krolov** [comment]
@bennycode hi thanks for the update.
I'm ready to do it but @balthazar usually worries about back compatibility. So if @balthazar is ready I'll do it.

**Comment by balthazar** [comment]
No it's fine you can remove it

**Comment by krolov** [comment]
@balthazar done

**Comment by balthazar** [comment]
Thanks!

**Pull request merged**
