### PR TITLE
Fixed type definitions for symbol filters.

### PR DESCRIPTION
**Pull request by malikfaik**
**This PR does the following changes in brief:**
- Updates the type definition for `Symbol.filters`

**Details:**

The previous type definition for filters to support discriminated union didn't work because to allow typescript to choose the correct interface two rules need to be followed:
1) There should be a common member between the interfaces.
2) The **value** of the common member should be unique per interface.

The definition was not following (2) as a result Typescript was failing with Type Errors.
Screenshot from 2021-05-23 16-22-06

This PR remedies (2) by moving the `filterType` values into their respective interfaces.

### CODE REVIEW

**Comment by balthazar** [comment]
@bennycode thoughts?

**Comment by bennycode** [comment]
@malikfaik can you create an enum for `SymbolFilterType`, so that it becomes easy for developers to consume it in their own applications?

I would like people to check properties with:

```
filterType === SymbolFilterType.PRICE_FILTER
```

**Review by bennycode — APPROVED** [review]
Thanks for implementing my comments. Looks good to me! 👍

**Comment by malikfaik** [comment]
Thanks for approving :smile: 

**Just a side note:** 

The rest of the definition still uses unions instead of enums, with this change we have now introduced an inconsistency with the rest of the types. It would be nice to do it for the everything else as well. ( If I get some time, I will do it ) 

Also, now with this change to `enums` , when someone updates to this version, they will most likely end up with type errors as strings and enums are not compatible with each other, a heads up in release notes would be nice.

**Comment by balthazar** [comment]
Thanks

Hum, I'm a bit hesitant to draft a breaking version if we are not consistent on our types, and would require subsequent breaking change versions if we update them. How much work would it be to upgrade everything to enums?

**Comment by malikfaik** [comment]
Changes:
- Updated all union types to enums.
- Changed `"true" | "false"` union type to boolean ( We are string enconding these fields into the url before sending the request, so it doesn't matter if it's boolean or string )

FYI @balthazar @bennycode

**Comment by balthazar** [comment]
Looks nice, sorry I forgot to remerge this, do you mind fixing the conflicts?

**Comment by malikfaik** [comment]
Fixed the conflicts :)

**Comment by balthazar** [comment]
@bennycode looking good?

**Comment by bennycode** [comment]
Looks good! 👍

**Comment by balthazar** [comment]
Thanks to you both 💯

**Pull request merged**
