### PR TITLE
Add Query Isolated Margin Account Info

### PR DESCRIPTION
**Pull request by krolov**
Link for documentation
https://binance-docs.github.io/apidocs/spot/en/#query-isolated-margin-account-info-user_data

### CODE REVIEW

**Comment by krolov** [comment]
@balthazar could you merge it, please?

**Comment by krolov** [comment]
@balthazar could you merge it, please?

**Comment by balthazar** [comment]
Hey can you remove the Info suffix of the name? I think `marginIsolatedAccount` is big and descriptive enough 😄

**Comment by krolov** [comment]
@balthazar done!

btw there is some mess in the margin trade. When I have time (never) I'll fix it

**Comment by balthazar** [comment]
Thanks 😄

**Pull request merged**
