### PR TITLE
Futures Support in progress

### PR DESCRIPTION
**Pull request by aneopsy**
Add all public REST API for futures:

 *   futuresPing
 *   futuresTime
 *   futuresExchangeInfo
 *   futuresBook
 *   futuresAggTrades
 *   futuresMarkPrice
 *   futuresAllForceOrders
 *   futuresCandles
 *   futuresTrades
 *   futuresDailyStats
 *   futuresPrices
 *   futuresAllBookTickers
 *   futuresFundingRate

Add some private REST API for futures:
*    futuresOrder
*    futuresCancelOrder
*    futuresOpenOrders
*    futuresPositionRisk
 
Add tests for all public REST API method.

### CODE REVIEW

**Comment by balthazar** [comment]
Salut et merci for the awesome contrib'!

I actually quite liked the idea proposed [here](https://github.com/Ashlar/binance-api-node/issues/220#issuecomment-563898278) by @hunsoo to have the endpoints organized by type of accounts. Since most of the endpoints are the same and the only difference is the parent endpoint of the url, we could avoid a lot of code duplication.

Let me know if that's too much and I'll take care of it in the future and probably draft a `0.10` release for it since it would be a breaking change.

**Comment by aneopsy** [comment]
Salut :)
I can work on it, JS is not my main language but it would be fine.

**Comment by balthazar** [comment]
Nah don't worry I think I prefer to work on it anyway. If you do not have any other updates to the initial PR I'll take a look today or tomorrow and merge it when I'm comfortable with it

**Comment by davydof** [comment]
@balthazar 
hey, could you please take a look on PR?
friendly ping :)

**Comment by balthazar** [comment]
Looks good! Very sorry for the delay in testing / merging 😞

**Comment by aneopsy** [comment]
If I have some time next week I will start to implement the idea proposed by @hunsoo.
Enjoy :)

**Pull request merged**
